### ISSUE TITLE
%DIR set incorrectly after @TEST-START-NEXT

### ISSUE THREAD

**Issue by ckreibich** [zeek/btest#11]
I think there might be a problem with the `%DIR` value: when using it in `@TEST-EXEC` statements the value seems to differ in test executions after a `@TEST-START-NEXT`. Since the source directory for such tests is the same, this shouldn't be happening, right?

I'm attaching a demo, see [example.zip](https://github.com/zeek/btest/files/2959307/example.zip)
```
$ unzip example.zip
Archive:  example.zip
   creating: example/
   creating: example/tests/
  inflating: example/tests/test.sh
  inflating: example/btest.cfg

$ cd example
$ cat tests/test.sh
# @TEST-EXEC: echo %DIR
# @TEST-START-NEXT

$ btest -A -t
[  0%] tests.test ... ok
[ 50%] tests.test-2 ... ok
all 2 tests successful

$ cat .tmp/tests.test/.stdout
/home/christian/tmp/example/tests

$ cat .tmp/tests.test-2/.stdout
/home/christian/tmp/example
```
It looks like in the tests following the first one, `%DIR` is just `%(testbase)s`, but I didn't dig in. I did verify though that at least in Zeek we currently have no btests using both `%DIR` and `@TEST-START-NEXT`....

**Comment by jsiwek** [comment]
My expectation would be that it uses the same dir value just as you expected, too.  So seems like a bug.
