### ISSUE TITLE
Support for multiple btest baselines

### ISSUE THREAD

**Issue by vpax** [zeek/btest#32]
I'd like to be able to use `btest`'s `--alternative` option as a way to conduct testing of Zeek options that alter Zeek's behavior on only a small number of tests, and for which I'd like to make sure that on the bulk of the tests the options don't result in any changes.  While there's already a notion in `btest` of alternative baselines (via `BTEST_TEST_BASE`), that changes the entire baseline.  What I want instead is essentially a series of baseline directories that are searched first-to-last.  With that, then I can put updates for the given Zeek option in `Baseline.my_alternative/` and confine what goes in there to just the differences, still picking up the bulk of the baseline from the default `Baseline/`.  I'd also want `btest -u` to update into the alternative Baseline rather than the original.

**Comment by rsmmr** [comment]
I'll give this a try.

**Comment by rsmmr** [comment]
This has landed.
