### ISSUE TITLE
CTRL-C of an unparallelized btest run doesn't work

### ISSUE THREAD

**Issue by ckreibich** [zeek/btest#35]
On a "normal", unparallelized btest run (one without -j) nothing happens when I hit CTRL-C. I'm attaching a really small example to demonstrate. It contains a single test that just sleeps for 10 seconds, and that test just keeps going:

```
$ unzip testsuite.zip
$ cd testsuite
$ btest
[  0%] tests.test1 ...^C^C^C^C^C^C^C^C^C
```
Eventually the 10 seconds are up and I get

```all 1 tests successful```

I see this also with the Zeek testsuite, for example. The root cause seems to be that we block `SIGINT` in `TestManager.threadRun()`, and in unparallelized operation `threadRun()` doesn't execute in a `multiprocessing` child process, but the main one. I looked at a few options for fixing this, and everything I try ends up being ugly and adding a bunch of complexity. Essentially, once I remove the ignoring of `SIGINT`, handling `KeyboardInterrupt` either happens "too low" in the stack, meaning we just skip the current test and continue with the next (I'm not seeing a clean way to signal exit to the manager, other than abuse of `Options.abort_on_failure`?) or "too high", meaning multiprocessing stuff doesn't get cleaned up properly (I'm seeing the subprocess created in `runSubprocess()` continuing, even though its child properly exits).

Now ... the good news is that when I run btest with `-j 1`, i.e. not parallelized but multi-processed, everything works fine. CTRL-C makes btest exit cleanly (I get the cursor back, a correct summary message regarding tests that have completed at this point, the various processes/threads clean themselves up, etc). So I am wondering whether instead of contorting ourselves to support unparallelized operation, we should just default to j = 1 instead of j = 0, and remove a bit of code. Or perhaps I'm just not seeing the right fix.

Also, I believe @rsmmr observed that CTRL-C actually does work for him, and I'm now quite curious why. :-)

I'm on Linux, Python 3.9, fwiw.

[testsuite.zip](https://github.com/zeek/btest/files/5599716/testsuite.zip)

**Comment by bbannier** [comment]
I believe what you are seeing is that <kbd>CTRL</kbd>-<kbd>C</kbd> only terminates `btest` after the current test has run to completion. You can confirm that by creating a second test and checking <kbd>CTRL</kbd>-<kbd>C</kbd> behavior:

```.sh
$ cp tests/test1.sh tests/test2.sh
$ time btest -v
tests.test1 ...
  > sleep 10
^CAborted.
btest -v  0.09s user 0.09s system 1% cpu 10.156 total
```

55c6ac279769d97d7d6eed83b239e4c9bc5bd09f changed the behavior of the parallel runner when encountering keyboard interrupts in that we now try to explicitly terminate workers though I think the forked processes still run to completion in a detached state. If this issue here gets fixed we might be able to properly terminate forked processes when running in parallel as well.

**Comment by ckreibich** [comment]
Thanks @bbannier ... unfortunately that isn't what I'm seeing — multiple tests still get executed after a CTRL-C:

```$ time btest -v
tests.test1 ...
  > sleep 10
^C^C^C... tests.test1 ok
tests.test2 ...
  > sleep 10
^C^C^C^C^C... tests.test2 ok
all 2 tests successful

real    0m20.202s
user    0m0.141s
sys     0m0.061s
```
> I think the forked processes still run to completion in a detached state

Yeah, I can confirm that, and Robin had also mentioned that.

**Comment by ckreibich** [comment]
More evidence that this is Linux-specific: on FreeBSD 12.1 CTRL-C leads to exit once the current test has completed, just as you observe @bbannier.

**Comment by ckreibich** [comment]
This FreeBSD behavior is due to the fact that the CTRL-C leads to an IOError, which we catch all the way at the toplevel. Apparently this doesn't happen on Linux. So at least that difference is resolved.

**Comment by rsmmr** [comment]
Sounds like a platform-specific mess. :) The original suggestions of just defaulting to `j=1` sounds good to me, let's just get rid of the the non-threaded mode altogether. That will simplify the code and make things consistent across platforms.
