### ISSUE TITLE
Option '--abort-on-failure' does not ignore known failures

### ISSUE THREAD

**Issue by bbannier** [zeek/btest#36]
7d34baef867aab0496e4adbe3c8e76abc0abb97e introduced the `--abort-on-failure` option which aborts processing as soon as the first failing test is encountered. Currently it has no special handling for known failures (tests marked with `@TEST-KNOWN-FAILURE`) and will abort processing whenever they are encountered, i.e., they are treated as true failures. This seems counterintuitive as globally BTest would not count such tests as failures in that even with such tests failing the global status could still be success.

**Comment by rsmmr** [comment]
See if #37  fixes this for you.
