### ISSUE TITLE
No error/warning for nonexistent alternative

### ISSUE THREAD

**Issue by jsiwek** [zeek/btest#40]
Requesting an alternative name that nothing uses provides no indication about that:

```
$ btest --show-all --alternative=foo,asdf  tests/basic-succeed.test
[  0%] tests.basic-succeed [foo] ... ok
[100%] tests.basic-succeed [asdf] ... ok
all 2 tests successful
```

Nothing's been defined for the `foo` or `asdf` alternatives, but it may have reverted back to running the standard config and said they were "successful".  Seems preferable to have this be an error rather than running `btest -a typo` and being fooled into thinking a test suite passes when it actually doesn't.

**Comment by awelzel** [comment]
This seems to have been fixed with: fe8c40b983b71434264d1636ccd296bc3545fac8
