### ISSUE TITLE
BTest hangs waiting for child processes

### ISSUE THREAD

**Issue by bbannier** [zeek/btest#43]
Since 2a6a88e53547cd4539aff654a83620e43976f1d5 we over in zeek/spicy seem to observe more hangs in our alpine-3.12 build (which uses musl as libc). This build was always slow, but now seems to sometimes hang completely.

I was able to bisect this with the following setup

- use branch from zeek/spicy#652
- build alpine Docker image: `cd docker && make build-alpine-3.12`
- insider the Docker container: `make run-alpine-3.12` with Docker set up up provide just 4 CPUs:
  - execute the zeek part of the test suite: `cd /opt/spicy/src/tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy ~/btest/btest -a installation -d -j 8 zeek` (note `-j 8` even though container has only 4 CPUs)

This executes 25 test jobs (more than `ncpus=4` or `-j 8`), puts considerable strain on the CPU and has each test forking additional subprocesses. With that I see reliable hangs with the tip of the branch from zeek/spicy#652 which first appear with zeek/btest@2a6a88e53547cd4539aff654a83620e43976f1d5. I compared that commit its precursor, but nothing jump out, yet.

The symptoms are:

- BTest stops making progress
- the forked processes stop consuming CPU suggesting they finished
- `gdb` indicates that the btest threads are blocking on `waitpid`
- running BTest under `pdb` also leads to a hang, but trying to examine the state by breaking into the debugger with ctrl-c makes the process finish successfully.

**Comment by rsmmr** [comment]
Random shot into the dark: can you try revert this one

```
@@ -2555,7 +2560,9 @@ try:
         if len(addr) > 100:
             addr = os.path.join("/tmp", sname)

-    (succeeded, failed, skipped, unstable, failed_expected) = TestManager(address=addr).run(copy.deepcopy(tests), output_handler)
+    mgr = TestManager(address=addr)
+    (succeeded, failed, skipped, unstable, failed_expected) = mgr.run(
+        copy.deepcopy(tests), output_handler)
     total = succeeded + failed + skipped
     output_handler.finished()
```

**Comment by bbannier** [comment]
> Random shot into the dark: can you try revert this one

This does not seem to fix it.

**Comment by bbannier** [comment]
After looking into the processes BTest waits on I now believe this is not a BTest bug, but instead an issue in zeek/spicy#652 where it fails to collect the status of forked processes. Closing for now.
